D1215 03:12:59.688752 12298 glog.py:118] Log level set to DEBUG
Traceback (most recent call last):
  File "main.py", line 496, in <module>
    app()
  File "/home/benoit/programmation/chdrft/main.py", line 80, in __call__
    main_func()
  File "main.py", line 493, in main
    ActionHandler.Run(ctx)
  File "/home/benoit/programmation/chdrft/utils/cmdify.py", line 242, in Run
    ActionHandler.g_handler.proc(app.flags, caller_ctx, *args, **kwargs)
  File "/home/benoit/programmation/chdrft/utils/cmdify.py", line 193, in proc
    self.do_proc(stack, flags, *args, **kwargs)
  File "/home/benoit/programmation/chdrft/utils/cmdify.py", line 169, in do_proc
    res = self.execute_action(action)
  File "/home/benoit/programmation/chdrft/utils/cmdify.py", line 232, in execute_action
    return action.func(*self.args, **self.kwargs)
  File "main.py", line 115, in test2
    solve_content = Format(solve_content).pad(findit_offset).v
TypeError: pad() missing 1 required positional argument: 'fill'
